[project]
name = "spend-growth-management-simulator"
version = "0.1.0"
description = "Spend Growth Management (SGM) Simulator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.28.0",
    "plotly>=5.19.0",
    "pytest>=7.0.0",
    "numpy>=1.26.0",
]
